### PR TITLE
[ENTESB-10146] Print name of secret instead of boolean

### PR DESCRIPTION
**Pull request by llowinge**
https://issues.jboss.org/browse/ENTESB-10146

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by KurtStam** [comment]
@llowinge Seems like a huge security issue to print out a secret. Don't think we should do this no matter how convenient it is.

**Comment by llowinge** [comment]
Hi @KurtStam the `pullSecretName` is only name, right ? You had printed it also in https://github.com/jboss-fuse/fabric8-maven-plugin/blob/efc51cad29ed331c1c4eee2447ecc6693c8b99d6/core/src/main/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildService.java#L377 so i don't see the security risk here.

**Comment by KurtStam** [comment]
@llowinge Yes I misread, it's just the name of the secret. I had already deleted my comment :). All good with me!

**Comment by llowinge** [comment]
@KurtStam ahh, np, ok thank you

**Pull request merged**
